"""Publication protocol and manuscript-evidence contracts."""

from neuroselect.publication.analysis import (
    DEFAULT_PUBLICATION_ANALYSIS_CONFIG,
    PublicationAnalysisResult,
    PublicationAnalysisSpec,
    build_publication_analysis,
    load_publication_analysis_spec,
    read_publication_analysis,
    write_publication_analysis,
)
from neuroselect.publication.display import (
    DEFAULT_PUBLICATION_DISPLAY_CONFIG,
    PublicationDisplayInventory,
    PublicationDisplaySource,
    PublicationDisplaySpec,
    PublicationTable,
    RenderedPublicationFigure,
    load_publication_display_spec,
    read_publication_display,
    write_publication_display,
)
from neuroselect.publication.latex import (
    LatexManuscript,
    render_bibliography,
    render_latex_manuscript,
)
from neuroselect.publication.manuscript import (
    DEFAULT_MANUSCRIPT_CONFIG,
    ManuscriptClaim,
    ManuscriptClaimAudit,
    ManuscriptInventory,
    ManuscriptReference,
    ManuscriptSpec,
    audit_claims,
    citation_order,
    load_claim_ledger,
    load_manuscript_spec,
    load_references,
    read_manuscript_bundle,
    replace_citations,
    validate_manuscript_markers,
    verify_manuscript_inputs,
    write_manuscript_bundle,
)
from neuroselect.publication.protocol import (
    DEFAULT_PUBLICATION_PROTOCOL,
    PublicationProtocolAssessment,
    PublicationProtocolSpec,
    assess_publication_protocol,
    load_publication_protocol,
)

__all__ = [
    "DEFAULT_MANUSCRIPT_CONFIG",
    "DEFAULT_PUBLICATION_ANALYSIS_CONFIG",
    "DEFAULT_PUBLICATION_DISPLAY_CONFIG",
    "DEFAULT_PUBLICATION_PROTOCOL",
    "LatexManuscript",
    "ManuscriptClaim",
    "ManuscriptClaimAudit",
    "ManuscriptInventory",
    "ManuscriptReference",
    "ManuscriptSpec",
    "PublicationAnalysisResult",
    "PublicationAnalysisSpec",
    "PublicationDisplayInventory",
    "PublicationDisplaySource",
    "PublicationDisplaySpec",
    "PublicationProtocolAssessment",
    "PublicationProtocolSpec",
    "PublicationTable",
    "RenderedPublicationFigure",
    "assess_publication_protocol",
    "audit_claims",
    "build_publication_analysis",
    "citation_order",
    "load_claim_ledger",
    "load_manuscript_spec",
    "load_publication_analysis_spec",
    "load_publication_display_spec",
    "load_publication_protocol",
    "load_references",
    "read_manuscript_bundle",
    "read_publication_analysis",
    "read_publication_display",
    "render_bibliography",
    "render_latex_manuscript",
    "replace_citations",
    "validate_manuscript_markers",
    "verify_manuscript_inputs",
    "write_manuscript_bundle",
    "write_publication_analysis",
    "write_publication_display",
]
